// Build-time version injection: write package.json's version into src/version.ts
// (the bundled plugin can't reliably read package.json at runtime).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));

const contents =
  `// AUTO-GENERATED by scripts/inject-version.mjs — do not edit by hand.\n` +
  `export const INTEGRATION_VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(path.join(root, "src", "version.ts"), contents);
console.error(`inject-version: INTEGRATION_VERSION=${pkg.version}`);
